config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get path directed to welcome controller, home action
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources 'users', except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer>
        <small>
            Copyright &copy;
        </small>
        <nav>
            <ul>
                <li>
                    <%= link_to "About", about_path %>
                </li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
    <div class="row">
        
        <% flash.each do |name, msg| %>
            
            <div class="col-sm-4 offset-sm-4 alert alert-<%="#{name}"%> alert-dismissible fade show" role="alert">

                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
        <% end %>
        
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Kurt's Blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "Articles", articles_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Users", users_path, class: "nav-link" %>
            </li>
            <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Actions
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a><%= link_to "New Article", new_article_path, class: "dropdown-item" %></a>
                </div>
            </li>
        <% end %>
        </ul>

        <% if logged_in? %>
            <a href="#"><%= link_to 'Log Out', logout_path, method: :delete, class: "nav-link" %> </a>
        <div class="dropdown">
            <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Your <%= "Admin" if current_user.admin? %> Profile
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item " href="#"><%= link_to 'Edit Profile', edit_user_path(current_user), class: "dropdown-item dropdown-nav-link"  %></a>
                <a class="dropdown-item" href="#"><%= link_to 'View Profile', user_path(current_user), class: "dropdown-item  dropdown-nav-link" %></a>
            </div>
        </div>
        <% else%>
        <a href="#"><%= link_to 'Log In', login_path,  class: "nav-link"  %> </a>
        <a href="#"><%= link_to 'Sign Up', signup_path,  class: "nav-link"  %> </a>
        <% end %>

</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% content_for :head do %>
    <title>MyRailsApp</title>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container" >
    <%= yield %>      
    </div>
    <%= render "layouts/footer" %>
    <!-- display DEBUGGER params, if Rails app in development -->
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>